// <auto-generated />
namespace Bgts.Gps.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_Tables_Fields_Nullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_Tables_Fields_Nullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201604180615268_Update_Tables_Fields_Nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
