namespace Bgts.Gps.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Update_Tables_Fields_Nullable : DbMigration
    {
        public override void Up()
        {
            DropIndex("dbo.ClientBranch", new[] { "ParentId" });
            DropIndex("dbo.CompanyEmployeeAbsence", new[] { "CompanyEmployeeId" });
            DropIndex("dbo.CompanyEmployee", new[] { "CityId" });
            DropIndex("dbo.CompanyEmployee", new[] { "AreaId" });
            DropIndex("dbo.CompanyEmployeeBan", new[] { "CompanyEmployeeId" });
            DropIndex("dbo.CompanyEmployeeBan", new[] { "ClientId" });
            DropIndex("dbo.CompanyEmployeeBan", new[] { "ClientBranchId" });
            DropIndex("dbo.CompanyEmployeeDaysNotAvailable", new[] { "CompanyEmployeeId" });
            DropIndex("dbo.CompanyEmployeeEmail", new[] { "CompanyEmployeeId" });
            DropIndex("dbo.CompanyEmployeePicture", new[] { "CompanyEmployeeId" });
            DropIndex("dbo.CompanyEmployeeSkill", new[] { "CompanyEmployeeId" });
            AlterColumn("dbo.City", "Country", c => c.String(nullable: false, maxLength: 8));
            AlterColumn("dbo.Timezone", "IsNegativeGMT", c => c.Boolean());
            AlterColumn("dbo.Timezone", "DaylightSaving", c => c.Int());
            AlterColumn("dbo.ClientBranch", "ParentId", c => c.Int());
            AlterColumn("dbo.ClientBranch", "Name", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.ClientBranch", "Address1", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.ClientBranch", "ContactName", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("dbo.ClientBranch", "ContactPhone", c => c.String(nullable: false, maxLength: 16));
            AlterColumn("dbo.ClientBranch", "ARAccountId", c => c.Int());
            AlterColumn("dbo.ClientBranch", "SalesAccountId", c => c.Int());
            AlterColumn("dbo.Client", "StartTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Client", "EndTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Client", "Zipcode", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.Client", "AltBillAddress", c => c.Boolean());
            AlterColumn("dbo.Client", "Email", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.Client", "ContactPhone", c => c.String(nullable: false, maxLength: 16));
            AlterColumn("dbo.Client", "EmergName", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("dbo.Company", "DefaultServiceType", c => c.Int());
            AlterColumn("dbo.CompanyBranch", "Code", c => c.String(maxLength: 128));
            AlterColumn("dbo.CompanyBranch", "ContactName", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("dbo.CompanyBranch", "ContactPhone", c => c.String(nullable: false, maxLength: 16));
            AlterColumn("dbo.CompanyBranchUser", "UserId", c => c.Long());
            AlterColumn("dbo.CompanyBranchUser", "CompanyBranchId", c => c.Int());
            AlterColumn("dbo.CompanyContact", "Department", c => c.Int());
            AlterColumn("dbo.CompanyContact", "ContactType", c => c.Int());
            AlterColumn("dbo.CompanyContact", "TelNo2Type", c => c.Int());
            AlterColumn("dbo.CompanyContact", "TelNo3Type", c => c.Int());
            AlterColumn("dbo.CompanyContact", "TelNo4Type", c => c.Int());
            AlterColumn("dbo.CompanyEmployeeAbsence", "CompanyEmployeeId", c => c.Long());
            AlterColumn("dbo.CompanyEmployeeAbsence", "Pending", c => c.Boolean());
            AlterColumn("dbo.CompanyEmployeeAbsence", "StartTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CompanyEmployeeAbsence", "EndTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CompanyEmployee", "CityId", c => c.Int());
            AlterColumn("dbo.CompanyEmployee", "AreaId", c => c.Int());
            AlterColumn("dbo.CompanyEmployee", "Gender", c => c.Boolean());
            AlterColumn("dbo.CompanyEmployee", "AutoCalcFirstDtWork", c => c.Boolean());
            AlterColumn("dbo.CompanyEmployee", "BackGroundVerified", c => c.Boolean());
            AlterColumn("dbo.CompanyEmployee", "Rehirable", c => c.Boolean());
            AlterColumn("dbo.CompanyEmployee", "Rating", c => c.Int());
            AlterColumn("dbo.CompanyEmployeeBan", "CompanyEmployeeId", c => c.Long());
            AlterColumn("dbo.CompanyEmployeeBan", "ClientId", c => c.Int());
            AlterColumn("dbo.CompanyEmployeeBan", "ClientBranchId", c => c.Int());
            AlterColumn("dbo.CompanyEmployeeDaysNotAvailable", "CompanyEmployeeId", c => c.Long());
            AlterColumn("dbo.CompanyEmployeeDaysNotAvailable", "DayOfWeek", c => c.Int());
            AlterColumn("dbo.CompanyEmployeeDaysNotAvailable", "StartTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CompanyEmployeeDaysNotAvailable", "EndTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CompanyEmployeeDaysNotAvailable", "OnCall", c => c.Boolean());
            AlterColumn("dbo.CompanyEmployeeEmail", "CompanyEmployeeId", c => c.Long());
            AlterColumn("dbo.CompanyEmployeeEmail", "Email", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.CompanyEmployeeEmail", "DisplayName", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("dbo.CompanyEmployeeEmail", "FirstName", c => c.String(nullable: false, maxLength: 16));
            AlterColumn("dbo.CompanyEmployeeEmail", "LastName", c => c.String(nullable: false, maxLength: 16));
            AlterColumn("dbo.CompanyEmployeePicture", "CompanyEmployeeId", c => c.Long());
            AlterColumn("dbo.CompanyEmployeePicture", "SeqNo", c => c.Int());
            AlterColumn("dbo.CompanyEmployeePicture", "FileName", c => c.String(maxLength: 64));
            AlterColumn("dbo.CompanyEmployeeSkill", "CompanyEmployeeId", c => c.Long());
            AlterColumn("dbo.CompanyEmployeeSkill", "CanExpiry", c => c.Boolean());
            AlterColumn("dbo.CompanyEmployeeTelephone", "SeqNo", c => c.Int());
            AlterColumn("dbo.CompanyEmployeeTelephone", "PhoneNo", c => c.String(nullable: false, maxLength: 16));
            AlterColumn("dbo.Patient", "Address", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.SecurityRequiredLocation", "City", c => c.String(nullable: false, maxLength: 32));
            AlterColumn("dbo.SecurityRequiredLocation", "State", c => c.String(nullable: false, maxLength: 32));
            CreateIndex("dbo.ClientBranch", "ParentId");
            CreateIndex("dbo.CompanyEmployeeAbsence", "CompanyEmployeeId");
            CreateIndex("dbo.CompanyEmployee", "CityId");
            CreateIndex("dbo.CompanyEmployee", "AreaId");
            CreateIndex("dbo.CompanyEmployeeBan", "CompanyEmployeeId");
            CreateIndex("dbo.CompanyEmployeeBan", "ClientId");
            CreateIndex("dbo.CompanyEmployeeBan", "ClientBranchId");
            CreateIndex("dbo.CompanyEmployeeDaysNotAvailable", "CompanyEmployeeId");
            CreateIndex("dbo.CompanyEmployeeEmail", "CompanyEmployeeId");
            CreateIndex("dbo.CompanyEmployeePicture", "CompanyEmployeeId");
            CreateIndex("dbo.CompanyEmployeeSkill", "CompanyEmployeeId");
        }
        
        public override void Down()
        {
            DropIndex("dbo.CompanyEmployeeSkill", new[] { "CompanyEmployeeId" });
            DropIndex("dbo.CompanyEmployeePicture", new[] { "CompanyEmployeeId" });
            DropIndex("dbo.CompanyEmployeeEmail", new[] { "CompanyEmployeeId" });
            DropIndex("dbo.CompanyEmployeeDaysNotAvailable", new[] { "CompanyEmployeeId" });
            DropIndex("dbo.CompanyEmployeeBan", new[] { "ClientBranchId" });
            DropIndex("dbo.CompanyEmployeeBan", new[] { "ClientId" });
            DropIndex("dbo.CompanyEmployeeBan", new[] { "CompanyEmployeeId" });
            DropIndex("dbo.CompanyEmployee", new[] { "AreaId" });
            DropIndex("dbo.CompanyEmployee", new[] { "CityId" });
            DropIndex("dbo.CompanyEmployeeAbsence", new[] { "CompanyEmployeeId" });
            DropIndex("dbo.ClientBranch", new[] { "ParentId" });
            AlterColumn("dbo.SecurityRequiredLocation", "State", c => c.String(maxLength: 64));
            AlterColumn("dbo.SecurityRequiredLocation", "City", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.Patient", "Address", c => c.String(nullable: false, maxLength: 512));
            AlterColumn("dbo.CompanyEmployeeTelephone", "PhoneNo", c => c.String(maxLength: 16));
            AlterColumn("dbo.CompanyEmployeeTelephone", "SeqNo", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyEmployeeSkill", "CanExpiry", c => c.Boolean(nullable: false));
            AlterColumn("dbo.CompanyEmployeeSkill", "CompanyEmployeeId", c => c.Long(nullable: false));
            AlterColumn("dbo.CompanyEmployeePicture", "FileName", c => c.String(maxLength: 16));
            AlterColumn("dbo.CompanyEmployeePicture", "SeqNo", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyEmployeePicture", "CompanyEmployeeId", c => c.Long(nullable: false));
            AlterColumn("dbo.CompanyEmployeeEmail", "LastName", c => c.String(maxLength: 16));
            AlterColumn("dbo.CompanyEmployeeEmail", "FirstName", c => c.String(maxLength: 16));
            AlterColumn("dbo.CompanyEmployeeEmail", "DisplayName", c => c.String(maxLength: 32));
            AlterColumn("dbo.CompanyEmployeeEmail", "Email", c => c.String(maxLength: 64));
            AlterColumn("dbo.CompanyEmployeeEmail", "CompanyEmployeeId", c => c.Long(nullable: false));
            AlterColumn("dbo.CompanyEmployeeDaysNotAvailable", "OnCall", c => c.Boolean(nullable: false));
            AlterColumn("dbo.CompanyEmployeeDaysNotAvailable", "EndTime", c => c.DateTime());
            AlterColumn("dbo.CompanyEmployeeDaysNotAvailable", "StartTime", c => c.DateTime());
            AlterColumn("dbo.CompanyEmployeeDaysNotAvailable", "DayOfWeek", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyEmployeeDaysNotAvailable", "CompanyEmployeeId", c => c.Long(nullable: false));
            AlterColumn("dbo.CompanyEmployeeBan", "ClientBranchId", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyEmployeeBan", "ClientId", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyEmployeeBan", "CompanyEmployeeId", c => c.Long(nullable: false));
            AlterColumn("dbo.CompanyEmployee", "Rating", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyEmployee", "Rehirable", c => c.Boolean(nullable: false));
            AlterColumn("dbo.CompanyEmployee", "BackGroundVerified", c => c.Boolean(nullable: false));
            AlterColumn("dbo.CompanyEmployee", "AutoCalcFirstDtWork", c => c.Boolean(nullable: false));
            AlterColumn("dbo.CompanyEmployee", "Gender", c => c.Boolean(nullable: false));
            AlterColumn("dbo.CompanyEmployee", "AreaId", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyEmployee", "CityId", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyEmployeeAbsence", "EndTime", c => c.DateTime());
            AlterColumn("dbo.CompanyEmployeeAbsence", "StartTime", c => c.DateTime());
            AlterColumn("dbo.CompanyEmployeeAbsence", "Pending", c => c.Boolean(nullable: false));
            AlterColumn("dbo.CompanyEmployeeAbsence", "CompanyEmployeeId", c => c.Long(nullable: false));
            AlterColumn("dbo.CompanyContact", "TelNo4Type", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyContact", "TelNo3Type", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyContact", "TelNo2Type", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyContact", "ContactType", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyContact", "Department", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyBranchUser", "CompanyBranchId", c => c.Int(nullable: false));
            AlterColumn("dbo.CompanyBranchUser", "UserId", c => c.Long(nullable: false));
            AlterColumn("dbo.CompanyBranch", "ContactPhone", c => c.String(maxLength: 16));
            AlterColumn("dbo.CompanyBranch", "ContactName", c => c.String(maxLength: 32));
            AlterColumn("dbo.CompanyBranch", "Code", c => c.String(maxLength: 95));
            AlterColumn("dbo.Company", "DefaultServiceType", c => c.Int(nullable: false));
            AlterColumn("dbo.Client", "EmergName", c => c.String(maxLength: 32));
            AlterColumn("dbo.Client", "ContactPhone", c => c.String(maxLength: 16));
            AlterColumn("dbo.Client", "Email", c => c.String(maxLength: 64));
            AlterColumn("dbo.Client", "AltBillAddress", c => c.String(maxLength: 64));
            AlterColumn("dbo.Client", "Zipcode", c => c.String(nullable: false));
            AlterColumn("dbo.Client", "EndTime", c => c.DateTime());
            AlterColumn("dbo.Client", "StartTime", c => c.DateTime());
            AlterColumn("dbo.ClientBranch", "SalesAccountId", c => c.Int(nullable: false));
            AlterColumn("dbo.ClientBranch", "ARAccountId", c => c.Int(nullable: false));
            AlterColumn("dbo.ClientBranch", "ContactPhone", c => c.String(maxLength: 16));
            AlterColumn("dbo.ClientBranch", "ContactName", c => c.String(maxLength: 32));
            AlterColumn("dbo.ClientBranch", "Address1", c => c.String(maxLength: 64));
            AlterColumn("dbo.ClientBranch", "Name", c => c.String(maxLength: 64));
            AlterColumn("dbo.ClientBranch", "ParentId", c => c.Int(nullable: false));
            AlterColumn("dbo.Timezone", "DaylightSaving", c => c.String(maxLength: 64));
            AlterColumn("dbo.Timezone", "IsNegativeGMT", c => c.Boolean(nullable: false));
            AlterColumn("dbo.City", "Country", c => c.String(maxLength: 8));
            CreateIndex("dbo.CompanyEmployeeSkill", "CompanyEmployeeId");
            CreateIndex("dbo.CompanyEmployeePicture", "CompanyEmployeeId");
            CreateIndex("dbo.CompanyEmployeeEmail", "CompanyEmployeeId");
            CreateIndex("dbo.CompanyEmployeeDaysNotAvailable", "CompanyEmployeeId");
            CreateIndex("dbo.CompanyEmployeeBan", "ClientBranchId");
            CreateIndex("dbo.CompanyEmployeeBan", "ClientId");
            CreateIndex("dbo.CompanyEmployeeBan", "CompanyEmployeeId");
            CreateIndex("dbo.CompanyEmployee", "AreaId");
            CreateIndex("dbo.CompanyEmployee", "CityId");
            CreateIndex("dbo.CompanyEmployeeAbsence", "CompanyEmployeeId");
            CreateIndex("dbo.ClientBranch", "ParentId");
        }
    }
}
