// <auto-generated />
namespace Bgts.Gps.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_CompanyBranchUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_CompanyBranchUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201604010926421_Update_CompanyBranchUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
